import { Teams, Departments } from "./employee.model";

export const EmployeeData = [
    {
      "employeeNo": "EMP1001",
      "name": "Andrew Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar.png",
      "designation": "Senior UI Developer",
      "rating": "3",
      "exp": "5 Years above",
      "doj": "2015",
      "currentTeam": Teams.IDC,
      "reportingManager": "Lalith Agarwal",
      "phone": "9922334455",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Full Time",
      "department": Departments.FEDEV
    },
    {
      "employeeNo": "EMP1002",
      "name": "John Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar2.png",
      "designation": "Technical Architect",
      "rating": "4",
      "exp": "5 Years above",
      "doj": "2015",
      "currentTeam": Teams.IDC,
      "reportingManager": "Smita Patel",
      "phone": "9922334451",
      "email": "andrew@infrrd.in",
      "location": "Hyderabad",
      "roleType": "Part Time",
      "department": Departments.MLENG
    },
    {
      "employeeNo": "EMP1003",
      "name": "Jane Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar.png",
      "designation": "Senior UI Developer",
      "rating": "4",
      "exp": "4 Years",
      "doj": "2017",
      "currentTeam": Teams.RDN,
      "reportingManager": "Lalith Agarwal",
      "phone": "9922334452",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Full Time",
      "department": Departments.MLENG
    },
    {
      "employeeNo": "EMP1004",
      "name": "Jessy Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar2.png",
      "designation": "Junior UI Developer",
      "rating": "4",
      "exp": "1 Year",
      "doj": "2019",
      "currentTeam": Teams.RTY,
      "reportingManager": "Lalith Agarwal",
      "phone": "9922334453",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Contract to Hire",
      "department": Departments.HRM
    },
    {
      "employeeNo": "EMP1005",
      "name": "Jean Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar2.png",
      "designation": "Technical Architect",
      "rating": "4",
      "exp": "5 Years above",
      "doj": "2016",
      "currentTeam": Teams.IDC,
      "reportingManager": "Lalith Agarwal",
      "phone": "9922334454",
      "email": "andrew@infrrd.in",
      "location": "Hyderabad",
      "roleType": "Part Time",
      "department": Departments.HRM
    },
    {
      "employeeNo": "EMP1006",
      "name": "Anne Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar.png",
      "designation": "QA Analyst Lead",
      "rating": "3",
      "exp": "4 Years",
      "doj": "2017",
      "currentTeam": Teams.OCBC,
      "reportingManager": "Smita Patel",
      "phone": "9922334456",
      "email": "andrew@infrrd.in",
      "location": "Chennai",
      "roleType": "Full Time",
      "department": Departments.QA
    },
    {
      "employeeNo": "EMP1007",
      "name": "Allison Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar2.png",
      "designation": "Junior UI Developer",
      "rating": "2",
      "exp": "2 Years",
      "doj": "2018",
      "currentTeam": Teams.OCBC,
      "reportingManager": "Akshay Mishra",
      "phone": "9922334457",
      "email": "andrew@infrrd.in",
      "location": "Hyderabad",
      "roleType": "Contract to Hire",
      "department": Departments.FEDEV
    },
    {
      "employeeNo": "EMP1008",
      "name": "Mike Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar.png",
      "designation": "Technical Architect",
      "rating": "4",
      "exp": "5 Years above",
      "doj": "2015",
      "currentTeam": Teams.RDN,
      "reportingManager": "Smita Patel",
      "phone": "9922334458",
      "email": "andrew@infrrd.in",
      "location": "Delhi",
      "roleType": "Full Time",
      "department": Departments.HRM
    },
    {
      "employeeNo": "EMP1009",
      "name": "Jack Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar2.png",
      "designation": "Technical Architect",
      "rating": "4",
      "exp": "5 Years above",
      "doj": "2016",
      "currentTeam": Teams.PT,
      "reportingManager": "Akshay Mishra",
      "phone": "9922334459",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Part Time",
      "department": Departments.MLENG
    },
    {
      "employeeNo": "EMP1010",
      "name": "Jill Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar.png",
      "designation": "Junior UI Developer",
      "rating": "3",
      "exp": "3 Years",
      "doj": "2017",
      "currentTeam": Teams.PT,
      "reportingManager": "Akshay Mishra",
      "phone": "9922334460",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Contract to Hire",
      "department": Departments.FEDEV
    },
    {
      "employeeNo": "EMP1011",
      "name": "Jay Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar2.png",
      "designation": "Senior UI Developer",
      "rating": "3",
      "exp": "5 Years above",
      "doj": "2015",
      "currentTeam": Teams.IDC,
      "reportingManager": "Lalith Agarwal",
      "phone": "9922334455",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Full Time",
      "department": Departments.FEDEV
    },
    {
      "employeeNo": "EMP1012",
      "name": "May Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar.png",
      "designation": "Senior UI Developer",
      "rating": "3",
      "exp": "5 Years above",
      "doj": "2015",
      "currentTeam": Teams.IDC,
      "reportingManager": "Lalith Agarwal",
      "phone": "9922334455",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Full Time",
      "department": Departments.FEDEV
    },
    {
      "employeeNo": "EMP1013",
      "name": "June Bidgen",
      "image": "https://www.w3schools.com/howto/img_avatar2.png",
      "designation": "Senior UI Developer",
      "rating": "3",
      "exp": "5 Years above",
      "doj": "2015",
      "currentTeam": Teams.IDC,
      "reportingManager": "Lalith Agarwal",
      "phone": "9922334455",
      "email": "andrew@infrrd.in",
      "location": "Bangalore",
      "roleType": "Full Time",
      "department": Departments.FEDEV
    },
  ];